// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: query.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XS2APIProtocol {

  /// <summary>Holder for reflection information generated from query.proto</summary>
  public static partial class QueryReflection {

    #region Descriptor
    /// <summary>File descriptor for query.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtxdWVyeS5wcm90bxIOWFMyQVBJUHJvdG9jb2waHnhzMmNsaWVudHByb3Rv",
            "Y29sL2NvbW1vbi5wcm90bxodeHMyY2xpZW50cHJvdG9jb2wvZXJyb3IucHJv",
            "dG8i8AEKDFJlcXVlc3RRdWVyeRI0CgdwYXRoaW5nGAEgAygLMiMuWFMyQVBJ",
            "UHJvdG9jb2wuUmVxdWVzdFF1ZXJ5UGF0aGluZxJBCglhYmlsaXRpZXMYAiAD",
            "KAsyLi5YUzJBUElQcm90b2NvbC5SZXF1ZXN0UXVlcnlBdmFpbGFibGVBYmls",
            "aXRpZXMSQQoKcGxhY2VtZW50cxgDIAMoCzItLlhTMkFQSVByb3RvY29sLlJl",
            "cXVlc3RRdWVyeUJ1aWxkaW5nUGxhY2VtZW50EiQKHGlnbm9yZV9yZXNvdXJj",
            "ZV9yZXF1aXJlbWVudHMYBCABKAgizgEKDVJlc3BvbnNlUXVlcnkSNQoHcGF0",
            "aGluZxgBIAMoCzIkLlhTMkFQSVByb3RvY29sLlJlc3BvbnNlUXVlcnlQYXRo",
            "aW5nEkIKCWFiaWxpdGllcxgCIAMoCzIvLlhTMkFQSVByb3RvY29sLlJlc3Bv",
            "bnNlUXVlcnlBdmFpbGFibGVBYmlsaXRpZXMSQgoKcGxhY2VtZW50cxgDIAMo",
            "CzIuLlhTMkFQSVByb3RvY29sLlJlc3BvbnNlUXVlcnlCdWlsZGluZ1BsYWNl",
            "bWVudCKKAQoTUmVxdWVzdFF1ZXJ5UGF0aGluZxIsCglzdGFydF9wb3MYASAB",
            "KAsyFy5YUzJBUElQcm90b2NvbC5Qb2ludDJESAASEgoIdW5pdF90YWcYAiAB",
            "KARIABIoCgdlbmRfcG9zGAMgASgLMhcuWFMyQVBJUHJvdG9jb2wuUG9pbnQy",
            "REIHCgVzdGFydCIoChRSZXNwb25zZVF1ZXJ5UGF0aGluZxIQCghkaXN0YW5j",
            "ZRgBIAEoAiIyCh5SZXF1ZXN0UXVlcnlBdmFpbGFibGVBYmlsaXRpZXMSEAoI",
            "dW5pdF90YWcYASABKAQifgofUmVzcG9uc2VRdWVyeUF2YWlsYWJsZUFiaWxp",
            "dGllcxIzCglhYmlsaXRpZXMYASADKAsyIC5YUzJBUElQcm90b2NvbC5BdmFp",
            "bGFibGVBYmlsaXR5EhAKCHVuaXRfdGFnGAIgASgEEhQKDHVuaXRfdHlwZV9p",
            "ZBgDIAEoDSJ6Ch1SZXF1ZXN0UXVlcnlCdWlsZGluZ1BsYWNlbWVudBISCgph",
            "YmlsaXR5X2lkGAEgASgFEisKCnRhcmdldF9wb3MYAiABKAsyFy5YUzJBUElQ",
            "cm90b2NvbC5Qb2ludDJEEhgKEHBsYWNpbmdfdW5pdF90YWcYAyABKAQiTgoe",
            "UmVzcG9uc2VRdWVyeUJ1aWxkaW5nUGxhY2VtZW50EiwKBnJlc3VsdBgBIAEo",
            "DjIcLlhTMkFQSVByb3RvY29sLkFjdGlvblJlc3VsdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::XS2APIProtocol.CommonReflection.Descriptor, global::XS2APIProtocol.ErrorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::XS2APIProtocol.RequestQuery), global::XS2APIProtocol.RequestQuery.Parser, new[]{ "Pathing", "Abilities", "Placements", "IgnoreResourceRequirements" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XS2APIProtocol.ResponseQuery), global::XS2APIProtocol.ResponseQuery.Parser, new[]{ "Pathing", "Abilities", "Placements" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XS2APIProtocol.RequestQueryPathing), global::XS2APIProtocol.RequestQueryPathing.Parser, new[]{ "StartPos", "UnitTag", "EndPos" }, new[]{ "Start" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XS2APIProtocol.ResponseQueryPathing), global::XS2APIProtocol.ResponseQueryPathing.Parser, new[]{ "Distance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XS2APIProtocol.RequestQueryAvailableAbilities), global::XS2APIProtocol.RequestQueryAvailableAbilities.Parser, new[]{ "UnitTag" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XS2APIProtocol.ResponseQueryAvailableAbilities), global::XS2APIProtocol.ResponseQueryAvailableAbilities.Parser, new[]{ "Abilities", "UnitTag", "UnitTypeId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XS2APIProtocol.RequestQueryBuildingPlacement), global::XS2APIProtocol.RequestQueryBuildingPlacement.Parser, new[]{ "AbilityId", "TargetPos", "PlacingUnitTag" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XS2APIProtocol.ResponseQueryBuildingPlacement), global::XS2APIProtocol.ResponseQueryBuildingPlacement.Parser, new[]{ "Result" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RequestQuery : pb::IMessage<RequestQuery> {
    private static readonly pb::MessageParser<RequestQuery> _parser = new pb::MessageParser<RequestQuery>(() => new RequestQuery());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestQuery> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XS2APIProtocol.QueryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQuery() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQuery(RequestQuery other) : this() {
      pathing_ = other.pathing_.Clone();
      abilities_ = other.abilities_.Clone();
      placements_ = other.placements_.Clone();
      ignoreResourceRequirements_ = other.ignoreResourceRequirements_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQuery Clone() {
      return new RequestQuery(this);
    }

    /// <summary>Field number for the "pathing" field.</summary>
    public const int PathingFieldNumber = 1;
    private static readonly pb::FieldCodec<global::XS2APIProtocol.RequestQueryPathing> _repeated_pathing_codec
        = pb::FieldCodec.ForMessage(10, global::XS2APIProtocol.RequestQueryPathing.Parser);
    private readonly pbc::RepeatedField<global::XS2APIProtocol.RequestQueryPathing> pathing_ = new pbc::RepeatedField<global::XS2APIProtocol.RequestQueryPathing>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::XS2APIProtocol.RequestQueryPathing> Pathing {
      get { return pathing_; }
    }

    /// <summary>Field number for the "abilities" field.</summary>
    public const int AbilitiesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::XS2APIProtocol.RequestQueryAvailableAbilities> _repeated_abilities_codec
        = pb::FieldCodec.ForMessage(18, global::XS2APIProtocol.RequestQueryAvailableAbilities.Parser);
    private readonly pbc::RepeatedField<global::XS2APIProtocol.RequestQueryAvailableAbilities> abilities_ = new pbc::RepeatedField<global::XS2APIProtocol.RequestQueryAvailableAbilities>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::XS2APIProtocol.RequestQueryAvailableAbilities> Abilities {
      get { return abilities_; }
    }

    /// <summary>Field number for the "placements" field.</summary>
    public const int PlacementsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::XS2APIProtocol.RequestQueryBuildingPlacement> _repeated_placements_codec
        = pb::FieldCodec.ForMessage(26, global::XS2APIProtocol.RequestQueryBuildingPlacement.Parser);
    private readonly pbc::RepeatedField<global::XS2APIProtocol.RequestQueryBuildingPlacement> placements_ = new pbc::RepeatedField<global::XS2APIProtocol.RequestQueryBuildingPlacement>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::XS2APIProtocol.RequestQueryBuildingPlacement> Placements {
      get { return placements_; }
    }

    /// <summary>Field number for the "ignore_resource_requirements" field.</summary>
    public const int IgnoreResourceRequirementsFieldNumber = 4;
    private bool ignoreResourceRequirements_;
    /// <summary>
    /// Ignores requirements like food, minerals and so on.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IgnoreResourceRequirements {
      get { return ignoreResourceRequirements_; }
      set {
        ignoreResourceRequirements_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestQuery);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestQuery other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pathing_.Equals(other.pathing_)) return false;
      if(!abilities_.Equals(other.abilities_)) return false;
      if(!placements_.Equals(other.placements_)) return false;
      if (IgnoreResourceRequirements != other.IgnoreResourceRequirements) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pathing_.GetHashCode();
      hash ^= abilities_.GetHashCode();
      hash ^= placements_.GetHashCode();
      if (IgnoreResourceRequirements != false) hash ^= IgnoreResourceRequirements.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      pathing_.WriteTo(output, _repeated_pathing_codec);
      abilities_.WriteTo(output, _repeated_abilities_codec);
      placements_.WriteTo(output, _repeated_placements_codec);
      if (IgnoreResourceRequirements != false) {
        output.WriteRawTag(32);
        output.WriteBool(IgnoreResourceRequirements);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += pathing_.CalculateSize(_repeated_pathing_codec);
      size += abilities_.CalculateSize(_repeated_abilities_codec);
      size += placements_.CalculateSize(_repeated_placements_codec);
      if (IgnoreResourceRequirements != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestQuery other) {
      if (other == null) {
        return;
      }
      pathing_.Add(other.pathing_);
      abilities_.Add(other.abilities_);
      placements_.Add(other.placements_);
      if (other.IgnoreResourceRequirements != false) {
        IgnoreResourceRequirements = other.IgnoreResourceRequirements;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            pathing_.AddEntriesFrom(input, _repeated_pathing_codec);
            break;
          }
          case 18: {
            abilities_.AddEntriesFrom(input, _repeated_abilities_codec);
            break;
          }
          case 26: {
            placements_.AddEntriesFrom(input, _repeated_placements_codec);
            break;
          }
          case 32: {
            IgnoreResourceRequirements = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ResponseQuery : pb::IMessage<ResponseQuery> {
    private static readonly pb::MessageParser<ResponseQuery> _parser = new pb::MessageParser<ResponseQuery>(() => new ResponseQuery());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseQuery> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XS2APIProtocol.QueryReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQuery() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQuery(ResponseQuery other) : this() {
      pathing_ = other.pathing_.Clone();
      abilities_ = other.abilities_.Clone();
      placements_ = other.placements_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQuery Clone() {
      return new ResponseQuery(this);
    }

    /// <summary>Field number for the "pathing" field.</summary>
    public const int PathingFieldNumber = 1;
    private static readonly pb::FieldCodec<global::XS2APIProtocol.ResponseQueryPathing> _repeated_pathing_codec
        = pb::FieldCodec.ForMessage(10, global::XS2APIProtocol.ResponseQueryPathing.Parser);
    private readonly pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryPathing> pathing_ = new pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryPathing>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryPathing> Pathing {
      get { return pathing_; }
    }

    /// <summary>Field number for the "abilities" field.</summary>
    public const int AbilitiesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::XS2APIProtocol.ResponseQueryAvailableAbilities> _repeated_abilities_codec
        = pb::FieldCodec.ForMessage(18, global::XS2APIProtocol.ResponseQueryAvailableAbilities.Parser);
    private readonly pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryAvailableAbilities> abilities_ = new pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryAvailableAbilities>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryAvailableAbilities> Abilities {
      get { return abilities_; }
    }

    /// <summary>Field number for the "placements" field.</summary>
    public const int PlacementsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::XS2APIProtocol.ResponseQueryBuildingPlacement> _repeated_placements_codec
        = pb::FieldCodec.ForMessage(26, global::XS2APIProtocol.ResponseQueryBuildingPlacement.Parser);
    private readonly pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryBuildingPlacement> placements_ = new pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryBuildingPlacement>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::XS2APIProtocol.ResponseQueryBuildingPlacement> Placements {
      get { return placements_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseQuery);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseQuery other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pathing_.Equals(other.pathing_)) return false;
      if(!abilities_.Equals(other.abilities_)) return false;
      if(!placements_.Equals(other.placements_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pathing_.GetHashCode();
      hash ^= abilities_.GetHashCode();
      hash ^= placements_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      pathing_.WriteTo(output, _repeated_pathing_codec);
      abilities_.WriteTo(output, _repeated_abilities_codec);
      placements_.WriteTo(output, _repeated_placements_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += pathing_.CalculateSize(_repeated_pathing_codec);
      size += abilities_.CalculateSize(_repeated_abilities_codec);
      size += placements_.CalculateSize(_repeated_placements_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseQuery other) {
      if (other == null) {
        return;
      }
      pathing_.Add(other.pathing_);
      abilities_.Add(other.abilities_);
      placements_.Add(other.placements_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            pathing_.AddEntriesFrom(input, _repeated_pathing_codec);
            break;
          }
          case 18: {
            abilities_.AddEntriesFrom(input, _repeated_abilities_codec);
            break;
          }
          case 26: {
            placements_.AddEntriesFrom(input, _repeated_placements_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///--------------------------------------------------------------------------------------------------
  /// </summary>
  public sealed partial class RequestQueryPathing : pb::IMessage<RequestQueryPathing> {
    private static readonly pb::MessageParser<RequestQueryPathing> _parser = new pb::MessageParser<RequestQueryPathing>(() => new RequestQueryPathing());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestQueryPathing> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XS2APIProtocol.QueryReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryPathing() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryPathing(RequestQueryPathing other) : this() {
      endPos_ = other.endPos_ != null ? other.endPos_.Clone() : null;
      switch (other.StartCase) {
        case StartOneofCase.StartPos:
          StartPos = other.StartPos.Clone();
          break;
        case StartOneofCase.UnitTag:
          UnitTag = other.UnitTag;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryPathing Clone() {
      return new RequestQueryPathing(this);
    }

    /// <summary>Field number for the "start_pos" field.</summary>
    public const int StartPosFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::XS2APIProtocol.Point2D StartPos {
      get { return startCase_ == StartOneofCase.StartPos ? (global::XS2APIProtocol.Point2D) start_ : null; }
      set {
        start_ = value;
        startCase_ = value == null ? StartOneofCase.None : StartOneofCase.StartPos;
      }
    }

    /// <summary>Field number for the "unit_tag" field.</summary>
    public const int UnitTagFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UnitTag {
      get { return startCase_ == StartOneofCase.UnitTag ? (ulong) start_ : 0UL; }
      set {
        start_ = value;
        startCase_ = StartOneofCase.UnitTag;
      }
    }

    /// <summary>Field number for the "end_pos" field.</summary>
    public const int EndPosFieldNumber = 3;
    private global::XS2APIProtocol.Point2D endPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::XS2APIProtocol.Point2D EndPos {
      get { return endPos_; }
      set {
        endPos_ = value;
      }
    }

    private object start_;
    /// <summary>Enum of possible cases for the "start" oneof.</summary>
    public enum StartOneofCase {
      None = 0,
      StartPos = 1,
      UnitTag = 2,
    }
    private StartOneofCase startCase_ = StartOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartOneofCase StartCase {
      get { return startCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearStart() {
      startCase_ = StartOneofCase.None;
      start_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestQueryPathing);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestQueryPathing other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(StartPos, other.StartPos)) return false;
      if (UnitTag != other.UnitTag) return false;
      if (!object.Equals(EndPos, other.EndPos)) return false;
      if (StartCase != other.StartCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (startCase_ == StartOneofCase.StartPos) hash ^= StartPos.GetHashCode();
      if (startCase_ == StartOneofCase.UnitTag) hash ^= UnitTag.GetHashCode();
      if (endPos_ != null) hash ^= EndPos.GetHashCode();
      hash ^= (int) startCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (startCase_ == StartOneofCase.StartPos) {
        output.WriteRawTag(10);
        output.WriteMessage(StartPos);
      }
      if (startCase_ == StartOneofCase.UnitTag) {
        output.WriteRawTag(16);
        output.WriteUInt64(UnitTag);
      }
      if (endPos_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(EndPos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (startCase_ == StartOneofCase.StartPos) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartPos);
      }
      if (startCase_ == StartOneofCase.UnitTag) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UnitTag);
      }
      if (endPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndPos);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestQueryPathing other) {
      if (other == null) {
        return;
      }
      if (other.endPos_ != null) {
        if (endPos_ == null) {
          EndPos = new global::XS2APIProtocol.Point2D();
        }
        EndPos.MergeFrom(other.EndPos);
      }
      switch (other.StartCase) {
        case StartOneofCase.StartPos:
          if (StartPos == null) {
            StartPos = new global::XS2APIProtocol.Point2D();
          }
          StartPos.MergeFrom(other.StartPos);
          break;
        case StartOneofCase.UnitTag:
          UnitTag = other.UnitTag;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::XS2APIProtocol.Point2D subBuilder = new global::XS2APIProtocol.Point2D();
            if (startCase_ == StartOneofCase.StartPos) {
              subBuilder.MergeFrom(StartPos);
            }
            input.ReadMessage(subBuilder);
            StartPos = subBuilder;
            break;
          }
          case 16: {
            UnitTag = input.ReadUInt64();
            break;
          }
          case 26: {
            if (endPos_ == null) {
              EndPos = new global::XS2APIProtocol.Point2D();
            }
            input.ReadMessage(EndPos);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ResponseQueryPathing : pb::IMessage<ResponseQueryPathing> {
    private static readonly pb::MessageParser<ResponseQueryPathing> _parser = new pb::MessageParser<ResponseQueryPathing>(() => new ResponseQueryPathing());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseQueryPathing> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XS2APIProtocol.QueryReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryPathing() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryPathing(ResponseQueryPathing other) : this() {
      distance_ = other.distance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryPathing Clone() {
      return new ResponseQueryPathing(this);
    }

    /// <summary>Field number for the "distance" field.</summary>
    public const int DistanceFieldNumber = 1;
    private float distance_;
    /// <summary>
    /// 0 if no path exists
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseQueryPathing);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseQueryPathing other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Distance, other.Distance)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Distance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Distance);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Distance != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Distance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Distance != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseQueryPathing other) {
      if (other == null) {
        return;
      }
      if (other.Distance != 0F) {
        Distance = other.Distance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            Distance = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///--------------------------------------------------------------------------------------------------
  /// </summary>
  public sealed partial class RequestQueryAvailableAbilities : pb::IMessage<RequestQueryAvailableAbilities> {
    private static readonly pb::MessageParser<RequestQueryAvailableAbilities> _parser = new pb::MessageParser<RequestQueryAvailableAbilities>(() => new RequestQueryAvailableAbilities());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestQueryAvailableAbilities> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XS2APIProtocol.QueryReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryAvailableAbilities() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryAvailableAbilities(RequestQueryAvailableAbilities other) : this() {
      unitTag_ = other.unitTag_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryAvailableAbilities Clone() {
      return new RequestQueryAvailableAbilities(this);
    }

    /// <summary>Field number for the "unit_tag" field.</summary>
    public const int UnitTagFieldNumber = 1;
    private ulong unitTag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UnitTag {
      get { return unitTag_; }
      set {
        unitTag_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestQueryAvailableAbilities);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestQueryAvailableAbilities other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnitTag != other.UnitTag) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnitTag != 0UL) hash ^= UnitTag.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnitTag != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UnitTag);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnitTag != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UnitTag);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestQueryAvailableAbilities other) {
      if (other == null) {
        return;
      }
      if (other.UnitTag != 0UL) {
        UnitTag = other.UnitTag;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UnitTag = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ResponseQueryAvailableAbilities : pb::IMessage<ResponseQueryAvailableAbilities> {
    private static readonly pb::MessageParser<ResponseQueryAvailableAbilities> _parser = new pb::MessageParser<ResponseQueryAvailableAbilities>(() => new ResponseQueryAvailableAbilities());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseQueryAvailableAbilities> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XS2APIProtocol.QueryReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryAvailableAbilities() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryAvailableAbilities(ResponseQueryAvailableAbilities other) : this() {
      abilities_ = other.abilities_.Clone();
      unitTag_ = other.unitTag_;
      unitTypeId_ = other.unitTypeId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryAvailableAbilities Clone() {
      return new ResponseQueryAvailableAbilities(this);
    }

    /// <summary>Field number for the "abilities" field.</summary>
    public const int AbilitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::XS2APIProtocol.AvailableAbility> _repeated_abilities_codec
        = pb::FieldCodec.ForMessage(10, global::XS2APIProtocol.AvailableAbility.Parser);
    private readonly pbc::RepeatedField<global::XS2APIProtocol.AvailableAbility> abilities_ = new pbc::RepeatedField<global::XS2APIProtocol.AvailableAbility>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::XS2APIProtocol.AvailableAbility> Abilities {
      get { return abilities_; }
    }

    /// <summary>Field number for the "unit_tag" field.</summary>
    public const int UnitTagFieldNumber = 2;
    private ulong unitTag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UnitTag {
      get { return unitTag_; }
      set {
        unitTag_ = value;
      }
    }

    /// <summary>Field number for the "unit_type_id" field.</summary>
    public const int UnitTypeIdFieldNumber = 3;
    private uint unitTypeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnitTypeId {
      get { return unitTypeId_; }
      set {
        unitTypeId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseQueryAvailableAbilities);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseQueryAvailableAbilities other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!abilities_.Equals(other.abilities_)) return false;
      if (UnitTag != other.UnitTag) return false;
      if (UnitTypeId != other.UnitTypeId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= abilities_.GetHashCode();
      if (UnitTag != 0UL) hash ^= UnitTag.GetHashCode();
      if (UnitTypeId != 0) hash ^= UnitTypeId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      abilities_.WriteTo(output, _repeated_abilities_codec);
      if (UnitTag != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(UnitTag);
      }
      if (UnitTypeId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(UnitTypeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += abilities_.CalculateSize(_repeated_abilities_codec);
      if (UnitTag != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UnitTag);
      }
      if (UnitTypeId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnitTypeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseQueryAvailableAbilities other) {
      if (other == null) {
        return;
      }
      abilities_.Add(other.abilities_);
      if (other.UnitTag != 0UL) {
        UnitTag = other.UnitTag;
      }
      if (other.UnitTypeId != 0) {
        UnitTypeId = other.UnitTypeId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            abilities_.AddEntriesFrom(input, _repeated_abilities_codec);
            break;
          }
          case 16: {
            UnitTag = input.ReadUInt64();
            break;
          }
          case 24: {
            UnitTypeId = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///--------------------------------------------------------------------------------------------------
  /// </summary>
  public sealed partial class RequestQueryBuildingPlacement : pb::IMessage<RequestQueryBuildingPlacement> {
    private static readonly pb::MessageParser<RequestQueryBuildingPlacement> _parser = new pb::MessageParser<RequestQueryBuildingPlacement>(() => new RequestQueryBuildingPlacement());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestQueryBuildingPlacement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XS2APIProtocol.QueryReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryBuildingPlacement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryBuildingPlacement(RequestQueryBuildingPlacement other) : this() {
      abilityId_ = other.abilityId_;
      targetPos_ = other.targetPos_ != null ? other.targetPos_.Clone() : null;
      placingUnitTag_ = other.placingUnitTag_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestQueryBuildingPlacement Clone() {
      return new RequestQueryBuildingPlacement(this);
    }

    /// <summary>Field number for the "ability_id" field.</summary>
    public const int AbilityIdFieldNumber = 1;
    private int abilityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AbilityId {
      get { return abilityId_; }
      set {
        abilityId_ = value;
      }
    }

    /// <summary>Field number for the "target_pos" field.</summary>
    public const int TargetPosFieldNumber = 2;
    private global::XS2APIProtocol.Point2D targetPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::XS2APIProtocol.Point2D TargetPos {
      get { return targetPos_; }
      set {
        targetPos_ = value;
      }
    }

    /// <summary>Field number for the "placing_unit_tag" field.</summary>
    public const int PlacingUnitTagFieldNumber = 3;
    private ulong placingUnitTag_;
    /// <summary>
    /// Not required
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong PlacingUnitTag {
      get { return placingUnitTag_; }
      set {
        placingUnitTag_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestQueryBuildingPlacement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestQueryBuildingPlacement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AbilityId != other.AbilityId) return false;
      if (!object.Equals(TargetPos, other.TargetPos)) return false;
      if (PlacingUnitTag != other.PlacingUnitTag) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AbilityId != 0) hash ^= AbilityId.GetHashCode();
      if (targetPos_ != null) hash ^= TargetPos.GetHashCode();
      if (PlacingUnitTag != 0UL) hash ^= PlacingUnitTag.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AbilityId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AbilityId);
      }
      if (targetPos_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetPos);
      }
      if (PlacingUnitTag != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(PlacingUnitTag);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AbilityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AbilityId);
      }
      if (targetPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetPos);
      }
      if (PlacingUnitTag != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PlacingUnitTag);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestQueryBuildingPlacement other) {
      if (other == null) {
        return;
      }
      if (other.AbilityId != 0) {
        AbilityId = other.AbilityId;
      }
      if (other.targetPos_ != null) {
        if (targetPos_ == null) {
          TargetPos = new global::XS2APIProtocol.Point2D();
        }
        TargetPos.MergeFrom(other.TargetPos);
      }
      if (other.PlacingUnitTag != 0UL) {
        PlacingUnitTag = other.PlacingUnitTag;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AbilityId = input.ReadInt32();
            break;
          }
          case 18: {
            if (targetPos_ == null) {
              TargetPos = new global::XS2APIProtocol.Point2D();
            }
            input.ReadMessage(TargetPos);
            break;
          }
          case 24: {
            PlacingUnitTag = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ResponseQueryBuildingPlacement : pb::IMessage<ResponseQueryBuildingPlacement> {
    private static readonly pb::MessageParser<ResponseQueryBuildingPlacement> _parser = new pb::MessageParser<ResponseQueryBuildingPlacement>(() => new ResponseQueryBuildingPlacement());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseQueryBuildingPlacement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XS2APIProtocol.QueryReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryBuildingPlacement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryBuildingPlacement(ResponseQueryBuildingPlacement other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseQueryBuildingPlacement Clone() {
      return new ResponseQueryBuildingPlacement(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::XS2APIProtocol.ActionResult result_ = global::XS2APIProtocol.ActionResult.ArError;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::XS2APIProtocol.ActionResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseQueryBuildingPlacement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseQueryBuildingPlacement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::XS2APIProtocol.ActionResult.ArError) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != global::XS2APIProtocol.ActionResult.ArError) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::XS2APIProtocol.ActionResult.ArError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseQueryBuildingPlacement other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::XS2APIProtocol.ActionResult.ArError) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::XS2APIProtocol.ActionResult) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
